#include <stdlib.h>
#include <stdio.h>

int main(int argc, const char* argv[]) {
    if (argc != 3) {
        printf("Parameter number incorrect\n");
        exit(1);
    }

    printf("/* File autogenerated. DO NOT MODIFY MANUALLY */\n");
    printf("\n");
    printf("#ifndef PYDTRACE_OFFSETS_H\n");
    printf("#define PYDTRACE_OFFSETS_H\n");
    printf("\n");
    printf("#define AFTER_PyEval_EvalFrameEx      %s\n", argv[1]);
    printf("#define AFTER_PyEval_EvalFrameExReal  %s\n", argv[2]);
    printf("\n");
    printf("#endif\n");
    return 0;
}

