/*
 * Generated by dtrace(1M).
 */

#ifndef _PYDTRACE_H
#define _PYDTRACE_H

#include <unistd.h>

#ifdef __cplusplus
extern "C" {
#endif

#if _DTRACE_VERSION

#define PYTHON_FUNCTION_ENTRY(arg0, arg1, arg2) \
  __dtrace_python___function__entry(arg0, arg1, arg2)
#define PYTHON_FUNCTION_ENTRY_ENABLED() \
  __dtraceenabled_python___function__entry()
#define PYTHON_FUNCTION_RETURN(arg0, arg1, arg2) \
  __dtrace_python___function__return(arg0, arg1, arg2)
#define PYTHON_FUNCTION_RETURN_ENABLED() \
  __dtraceenabled_python___function__return()


extern void __dtrace_python___function__entry(char *, char *, int);
extern int __dtraceenabled_python___function__entry(void);
extern void __dtrace_python___function__return(char *, char *, int);
extern int __dtraceenabled_python___function__return(void);

#else

#define PYTHON_FUNCTION_ENTRY(arg0, arg1, arg2)
#define PYTHON_FUNCTION_ENTRY_ENABLED() (0)
#define PYTHON_FUNCTION_RETURN(arg0, arg1, arg2)
#define PYTHON_FUNCTION_RETURN_ENABLED() (0)

#endif


#ifdef __cplusplus
}
#endif

#endif /* _PYDTRACE_H */
