/* Generated by the Systemtap dtrace wrapper */

#define _SDT_HAS_SEMAPHORES 1


#define STAP_HAS_SEMAPHORES 1 /* deprecated */


#include <sys/sdt.h>

/* PYTHON_FUNCTION_ENTRY ( const char *, const char *, int) */
#if defined STAP_SDT_V1
#define PYTHON_FUNCTION_ENTRY_ENABLED() __builtin_expect (function__entry_semaphore, 0)
#define python_function__entry_semaphore function__entry_semaphore
#else
#define PYTHON_FUNCTION_ENTRY_ENABLED() __builtin_expect (python_function__entry_semaphore, 0)
#endif
__extension__ extern unsigned short python_function__entry_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PYTHON_FUNCTION_ENTRY(arg1,arg2,arg3) \
DTRACE_PROBE3(python,function__entry,arg1,arg2,arg3)

/* PYTHON_FUNCTION_RETURN ( const char *, const char *, int) */
#if defined STAP_SDT_V1
#define PYTHON_FUNCTION_RETURN_ENABLED() __builtin_expect (function__return_semaphore, 0)
#define python_function__return_semaphore function__return_semaphore
#else
#define PYTHON_FUNCTION_RETURN_ENABLED() __builtin_expect (python_function__return_semaphore, 0)
#endif
__extension__ extern unsigned short python_function__return_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PYTHON_FUNCTION_RETURN(arg1,arg2,arg3) \
DTRACE_PROBE3(python,function__return,arg1,arg2,arg3)

/* PYTHON_INSTANCE_NEW_START ( const char *, const char *) */
#if defined STAP_SDT_V1
#define PYTHON_INSTANCE_NEW_START_ENABLED() __builtin_expect (instance__new__start_semaphore, 0)
#define python_instance__new__start_semaphore instance__new__start_semaphore
#else
#define PYTHON_INSTANCE_NEW_START_ENABLED() __builtin_expect (python_instance__new__start_semaphore, 0)
#endif
__extension__ extern unsigned short python_instance__new__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PYTHON_INSTANCE_NEW_START(arg1,arg2) \
DTRACE_PROBE2(python,instance__new__start,arg1,arg2)

/* PYTHON_INSTANCE_NEW_DONE ( const char *, const char *) */
#if defined STAP_SDT_V1
#define PYTHON_INSTANCE_NEW_DONE_ENABLED() __builtin_expect (instance__new__done_semaphore, 0)
#define python_instance__new__done_semaphore instance__new__done_semaphore
#else
#define PYTHON_INSTANCE_NEW_DONE_ENABLED() __builtin_expect (python_instance__new__done_semaphore, 0)
#endif
__extension__ extern unsigned short python_instance__new__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PYTHON_INSTANCE_NEW_DONE(arg1,arg2) \
DTRACE_PROBE2(python,instance__new__done,arg1,arg2)

/* PYTHON_INSTANCE_DELETE_START ( const char *, const char *) */
#if defined STAP_SDT_V1
#define PYTHON_INSTANCE_DELETE_START_ENABLED() __builtin_expect (instance__delete__start_semaphore, 0)
#define python_instance__delete__start_semaphore instance__delete__start_semaphore
#else
#define PYTHON_INSTANCE_DELETE_START_ENABLED() __builtin_expect (python_instance__delete__start_semaphore, 0)
#endif
__extension__ extern unsigned short python_instance__delete__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PYTHON_INSTANCE_DELETE_START(arg1,arg2) \
DTRACE_PROBE2(python,instance__delete__start,arg1,arg2)

/* PYTHON_INSTANCE_DELETE_DONE ( const char *, const char *) */
#if defined STAP_SDT_V1
#define PYTHON_INSTANCE_DELETE_DONE_ENABLED() __builtin_expect (instance__delete__done_semaphore, 0)
#define python_instance__delete__done_semaphore instance__delete__done_semaphore
#else
#define PYTHON_INSTANCE_DELETE_DONE_ENABLED() __builtin_expect (python_instance__delete__done_semaphore, 0)
#endif
__extension__ extern unsigned short python_instance__delete__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PYTHON_INSTANCE_DELETE_DONE(arg1,arg2) \
DTRACE_PROBE2(python,instance__delete__done,arg1,arg2)

/* PYTHON_LINE ( const char *, const char *, int) */
#if defined STAP_SDT_V1
#define PYTHON_LINE_ENABLED() __builtin_expect (line_semaphore, 0)
#define python_line_semaphore line_semaphore
#else
#define PYTHON_LINE_ENABLED() __builtin_expect (python_line_semaphore, 0)
#endif
__extension__ extern unsigned short python_line_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PYTHON_LINE(arg1,arg2,arg3) \
DTRACE_PROBE3(python,line,arg1,arg2,arg3)

/* PYTHON_GC_START ( int) */
#if defined STAP_SDT_V1
#define PYTHON_GC_START_ENABLED() __builtin_expect (gc__start_semaphore, 0)
#define python_gc__start_semaphore gc__start_semaphore
#else
#define PYTHON_GC_START_ENABLED() __builtin_expect (python_gc__start_semaphore, 0)
#endif
__extension__ extern unsigned short python_gc__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PYTHON_GC_START(arg1) \
DTRACE_PROBE1(python,gc__start,arg1)

/* PYTHON_GC_DONE ( long) */
#if defined STAP_SDT_V1
#define PYTHON_GC_DONE_ENABLED() __builtin_expect (gc__done_semaphore, 0)
#define python_gc__done_semaphore gc__done_semaphore
#else
#define PYTHON_GC_DONE_ENABLED() __builtin_expect (python_gc__done_semaphore, 0)
#endif
__extension__ extern unsigned short python_gc__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PYTHON_GC_DONE(arg1) \
DTRACE_PROBE1(python,gc__done,arg1)

